version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sistema_familiar_db
      - POSTGRES_USER=sistema_familiar_user
      - POSTGRES_PASSWORD=SuaSenhaSeguraParaDB2024
    ports:
      - "5440:5432"
    networks:
      - sistema-familiar-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema_familiar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    image: kbokleber/sistema-familiar:1.0.0
    entrypoint: ["/app/entrypoint.sh"]
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=maintenance_project.settings_prod
      - POSTGRES_DB=sistema_familiar_db
      - POSTGRES_USER=sistema_familiar_user
      - POSTGRES_PASSWORD=SuaSenhaSeguraParaDB2024
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - sistema-familiar-net

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  sistema-familiar-net:
    driver: overlay
    attachable: true