version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sistema_familiar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5440:5432"
    networks:
      - sistema-familiar-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema_familiar"]
      interval: 10s
      interval: 5s

  web:
    image: kbokleber/sistema-familiar:1.0.0
    entrypoint: ["/app/entrypoint.sh"]
    build: 
      context: .
      args:
        - VERSION=1.0.0
    image: kbokleber/sistema_familiar:1.0.0
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=maintenance_project.settings_prod
      - POSTGRES_DB=sistema_familiar_db
      - POSTGRES_USER=sistema_familiar_user
      - POSTGRES_PASSWORD=SuaSenhaSeguraParaDB2024
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=maintenance_project.settings_dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sistema_familiar
      - DOCKER_CONTAINER=true
      - POSTGRES_DB=sistema_familiar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - sistema-familiar-net

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  sistema-familiar-net:
    driver: overlay
    attachable: true