# Generated by Django 4.2.10 on 2025-03-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('relationship', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Tipo Sanguíneo')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Condições Crônicas')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='Contato de Emergência')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='Telefone de Emergência')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Membro da Família',
                'verbose_name_plural': 'Membros da Família',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200, verbose_name='Nome do Procedimento')),
                ('procedure_date', models.DateTimeField(verbose_name='Data do Procedimento')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='Nome do Médico')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('results', models.TextField(blank=True, verbose_name='Resultados')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='Observações de Acompanhamento')),
                ('next_procedure_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Próximo Procedimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.familymember', verbose_name='Membro da Família')),
            ],
            options={
                'verbose_name': 'Procedimento Médico',
                'verbose_name_plural': 'Procedimentos Médicos',
                'ordering': ['-procedure_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='Nome do Médico')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('appointment_date', models.DateTimeField(verbose_name='Data da Consulta')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('reason', models.TextField(verbose_name='Motivo da Consulta')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescrição')),
                ('next_appointment', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Consulta')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.familymember', verbose_name='Membro da Família')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
