# Generated by Django 4.2.10 on 2025-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_members/', verbose_name='Foto'),
        ),
    ]
