# Generated by Django 4.2.10 on 2025-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_familymember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato de Emergência'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Emergência'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco'),
        ),
    ]
