# Generated by Django 4.2.10 on 2025-03-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_alter_familymember_emergency_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Medicamento')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosagem')),
                ('frequency', models.CharField(choices=[('once', 'Uma vez ao dia'), ('twice', 'Duas vezes ao dia'), ('three_times', 'Três vezes ao dia'), ('four_times', 'Quatro vezes ao dia'), ('every_12h', 'A cada 12 horas'), ('every_8h', 'A cada 8 horas'), ('every_6h', 'A cada 6 horas'), ('every_4h', 'A cada 4 horas'), ('as_needed', 'Conforme necessário')], max_length=20, verbose_name='Frequência')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('prescribed_by', models.CharField(blank=True, max_length=100, verbose_name='Prescrito por')),
                ('prescription_number', models.CharField(blank=True, max_length=50, verbose_name='Número da Receita')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções Especiais')),
                ('side_effects', models.TextField(blank=True, verbose_name='Efeitos Colaterais')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='healthcare.familymember')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
