# Generated by Django 4.2.10 on 2025-03-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='family_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='healthcare.familymember', verbose_name='Membro da Família'),
        ),
    ]
