# Generated by Django 4.2.10 on 2025-03-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_familymember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='procedures/documents/', verbose_name='Arquivo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='healthcare.medicalprocedure', verbose_name='Procedimento')),
            ],
            options={
                'verbose_name': 'Documento do Procedimento',
                'verbose_name_plural': 'Documentos dos Procedimentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
