# Generated by Django 4.2.10 on 2025-03-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_appointmentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medication_documents/')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='healthcare.medication')),
            ],
            options={
                'verbose_name': 'Documento do Medicamento',
                'verbose_name_plural': 'Documentos dos Medicamentos',
            },
        ),
    ]
