# Generated by Django 4.2.10 on 2025-03-28 16:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthcare', '0011_medicationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=100)),
                ('exam_date', models.DateTimeField()),
                ('next_exam_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentdocument',
            name='file',
            field=models.FileField(upload_to='appointment_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='medicationdocument',
            name='file',
            field=models.FileField(upload_to='medication_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='proceduredocument',
            name='file',
            field=models.FileField(upload_to='procedure_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='healthcare.exam')),
            ],
        ),
    ]
