# Generated by Django 4.2.10 on 2025-04-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_alter_medication_start_date_and_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
    ]
