# Generated by Django 4.2.20 on 2025-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_remove_familymember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='photo_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo da Foto'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='photo',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Foto'),
        ),
    ]
