# Generated by Django 4.2.20 on 2025-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_familymember_photo_type_alter_familymember_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Membro da Família', 'verbose_name_plural': 'Membros da Família'},
        ),
        migrations.AddField(
            model_name='familymember',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
