# Generated by Django 4.2.10 on 2025-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenanceimage_maintenance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('eletronico', 'Eletrônico'), ('eletrodomestico', 'Eletrodoméstico'), ('movel', 'Móvel'), ('veiculo', 'Veículo'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='image',
            field=models.ImageField(upload_to='maintenance_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload'),
        ),
    ]
