# Generated by Django 4.2.10 on 2025-03-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_equipmentattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentattachment',
            name='description',
        ),
    ]
